<a href="https://colab.research.google.com/github/chanceCoderByPassion/DL_CV/blob/master/Intro_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSOR MANIPULATION


1.   reshaping
2.   joining
3.   splitting
4.   transposing
5.   permuting





In [1]:
import torch

In [6]:
# reshaping tensors
# reshape
# view
original_tensor = torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [8]:
reshaped_tensor = original_tensor.reshape(2,6)
print(reshaped_tensor)
print(reshaped_tensor.shape)
print(reshaped_tensor.ndim)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
2


In [9]:
reshaped_tensor = original_tensor.reshape(3,4)
print(reshaped_tensor)
print(reshaped_tensor.shape)
print(reshaped_tensor.ndim)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
2


In [14]:
# same as reshape but view has own contiguous memory
print(original_tensor.is_contiguous())
flattened_tensor = original_tensor.view(-1) #-1 means dimension calculated automatically by pytorch as vector
print(flattened_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [19]:
# slicing operation on tensor
tensor_a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)
print(tensor_a[0])# first row
print(tensor_a[:,-1])#last column

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2
tensor([1, 2, 3])
tensor([3, 6, 9])


In [20]:
sub_tensor = tensor_a[1:,1:]
print(sub_tensor)

tensor([[5, 6],
        [8, 9]])


JOINING TENSORS

In [21]:
#torch.cat() #--> merges tensors along an existing dimension
tensor_1 = torch.tensor([[1,2],[3,4]])
tensor_2 = torch.tensor([[5,6],[7,8]])
tensor_cat_rows=torch.cat((tensor_1,tensor_2),dim=0)
tensor_cat_cols=torch.cat((tensor_1,tensor_2),dim=1)
print(tensor_cat_rows)
print(tensor_cat_cols)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [24]:
# stack creates new dimesion which increases the tensors rank
tensor_stack_row = torch.stack((tensor_1,tensor_2),dim=0)
tensor_stack_col = torch.stack((tensor_1,tensor_2),dim=1)
print(tensor_stack_row)
print(tensor_stack_col)
print(tensor_stack_row.ndim)
print(tensor_stack_col.ndim)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])
3
3


SPLITTING TENSORS
-torch.chunk -- equal sized chunks
-torch.split -- uneven splitting as well

In [28]:
#torch.chunk
tensor_new = torch.arange(12)
tensor_chunks = torch.chunk(tensor_new,3,dim=0)#iterable
print(tensor_chunks)
for chunk in tensor_chunks:
  print(chunk)

(tensor([0, 1, 2, 3]), tensor([4, 5, 6, 7]), tensor([ 8,  9, 10, 11]))
tensor([0, 1, 2, 3])
tensor([4, 5, 6, 7])
tensor([ 8,  9, 10, 11])


In [30]:
# split
tensor_new = torch.arange(12)
tensor_splits = torch.split(tensor_new,7,dim=0)
print(tensor_splits)
for split in tensor_splits:
  print(split)

(tensor([0, 1, 2, 3, 4, 5, 6]), tensor([ 7,  8,  9, 10, 11]))
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([ 7,  8,  9, 10, 11])


TRANSPOSING AND PERMUTING
- transpose swaps dimensions
-permute rearranges all dimensions in specified order

In [31]:
original_tensor=torch.arange(24).reshape(12,2)
transposed_tensor = original_tensor.transpose(0,1)
print(transposed_tensor)
print(transposed_tensor.shape)

tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])
torch.Size([2, 12])


In [32]:
original_tensor=torch.arange(24).reshape(2,3,4)
permute_tensor=original_tensor.permute(2,0,1)
print(permute_tensor)
print(permute_tensor.shape)

tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])
torch.Size([4, 2, 3])


CLONING AND DETACHING

In [34]:
a=[1,2,3]
b=a
print(b)
a[0]=10
print(b)
import copy
c = copy.deepcopy(a)
print(c)
a[0]=100
print(c)

[1, 2, 3]
[10, 2, 3]
[10, 2, 3]
[10, 2, 3]


In [37]:
dummy_tensor  = torch.ones(3,3,requires_grad=True)# part of computation graph and shares unique memory
new_dummy = dummy_tensor.clone()
print(new_dummy)
detached_tensor = dummy_tensor.detach()# not a part of computation graph but storage will be same s the original one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], grad_fn=<CloneBackward0>)
