<a href="https://colab.research.google.com/github/chanceCoderByPassion/DL_CV/blob/master/Intro_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Accessing elements in a tensor
'''
tensor[row,column]
'''

In [4]:
import torch
vector = torch.tensor([[10,20,30],[40,50,60],[70,80,90]])
print(vector.ndim)
print(vector.shape)

2
torch.Size([3, 3])


In [9]:
print("element at (0,1)",vector[0])
print("Access first column",vector[:,0])

element at (0,1) tensor([10, 20, 30])
Access first column tensor([10, 40, 70])


In [10]:
# slicing operation
print("Elements from first two rows ",vector[:-1,:])

Elements from first two rows  tensor([[10, 20, 30],
        [40, 50, 60]])


In [11]:
print("First two columns:",vector[:,:-1])

First two columns: tensor([[10, 20],
        [40, 50],
        [70, 80]])


In [12]:
# Fancy Indexing
# (0,1)-->20
# (2,2)-->90

print("FancyIndexing:",vector[[0,2],[1,2]])

FancyIndexing: tensor([20, 90])


In [14]:
# Boolean Indexing
mask = vector > 50
print(mask)
print(vector[mask])

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [15]:
# Changing tensor values via indexing
print(vector)
vector[0,1] = 25
print(vector)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [16]:
vector[:,0] = torch.tensor([100,200,300])
print(vector)

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [17]:
indices = torch.tensor([0,2])
torch.index_select(vector,dim=0,index=indices)

tensor([[100,  25,  30],
        [300,  80,  90]])

In [18]:
# Access tensors with steps
print(vector[:,::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [20]:
torch.flip(vector,dims=(0,))

tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])