<a href="https://colab.research.google.com/github/chanceCoderByPassion/DL_CV/blob/master/Intro_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA TYPES FOR TENSORS
--floating -- for most DL tasks
--integer-- for categorical data and indices
--boolean-- for mask or logical operation
--complex-number-- for advanced computation
memory consumption - lesser precision lesser memory faster computation

In [2]:
import torch

In [4]:
default_tensor = torch.tensor([1.5,2.5,3.5])
print(default_tensor.dtype)

torch.float32


In [5]:
default_tensor = torch.tensor([1.5,2.5,3.5],dtype=torch.float64)
print(default_tensor.dtype)

torch.float64


In [7]:
default_tensor = torch.tensor([1.5,2.5,3.5],dtype=torch.int32)
print(default_tensor)
print(default_tensor.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [8]:
default_tensor = torch.tensor([1,2,3])
print(default_tensor)
print(default_tensor.dtype)

tensor([1, 2, 3])
torch.int64


In [9]:
default_tensor = torch.tensor([True,False,True])
print(default_tensor)
print(default_tensor.dtype)

tensor([ True, False,  True])
torch.bool


In [13]:
float_tensor = torch.tensor([1.5,2.5,3.5])
print(float_tensor)
print(float_tensor.dtype)
int_tensor = float_tensor.to(torch.int64)
print(int_tensor)
print(int_tensor.dtype)
int_tensor = torch.tensor([-1,0,1,2,0])
bool_tensor = int_tensor.to(torch.bool)
print(bool_tensor)
print(bool_tensor.dtype)

tensor([1.5000, 2.5000, 3.5000])
torch.float32
tensor([1, 2, 3])
torch.int64
tensor([ True, False,  True,  True, False])
torch.bool


IMPACT OF DATATYPE ON MEMORY

In [14]:
float32_tensor=torch.ones(1000,dtype=torch.float32)
float64_tensor=torch.ones(1000,dtype=torch.float64)
#tensor.element_size()-->size it takes for one element in bytes
#nelement --> number of elements in tensor
print(float32_tensor.element_size())
print(float32_tensor.nelement())
print("memory used by float32 tensor is:",float32_tensor.element_size()*float32_tensor.nelement())
print(float64_tensor.element_size())
print(float64_tensor.nelement())
print("memory used by float64 tensor is:",float64_tensor.element_size()*float32_tensor.nelement())

4
1000
memory used by float32 tensor is: 4000
8
1000
memory used by float64 tensor is: 8000


float32 --> default for most DL models
float64 --> for high precision computation
int32--> general purpose integer
int64--> used for tensor indices
bool-->mask and logical operation
float16--> half precision of default dtype,reduce memory usage on cpu/gpu
int8/int16--> used to reduce memory usage
complex64-->used for advanced computation


