<a href="https://colab.research.google.com/github/chanceCoderByPassion/DL_CV/blob/master/Intro_9_StackOperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

STACK OPERATION

In [1]:
import torch

In [2]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])
print(tensor_1.ndim)
print(tensor_1.size())


1
torch.Size([3])


In [4]:
stacked_tensor_dim0 = torch.stack((tensor_1,tensor_2),dim=0)
print(stacked_tensor_dim0.shape)
print(stacked_tensor_dim0)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
stacked_tensor_dim0 = torch.stack((tensor_1,tensor_2),dim=1)
print(stacked_tensor_dim0.shape)
print(stacked_tensor_dim0)

torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [7]:
tensor_3 = torch.tensor([7,8,9])
stacked_tensor = torch.stack((tensor_1,tensor_2,tensor_3),dim=1)
print(stacked_tensor.shape)
print(stacked_tensor)

torch.Size([3, 3])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [8]:
tensor_2d_1 = torch.tensor([[1,2],[3,4]])
tensor_2d_2 = torch.tensor([[5,6],[7,8]])
stacked_2d_tensor = torch.stack((tensor_2d_1,tensor_2d_2),dim=0)
print(stacked_2d_tensor.shape)
print(stacked_2d_tensor)

torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [9]:
stacked_2d_tensor2 = torch.stack((tensor_2d_1,tensor_2d_2),dim=1)
print(stacked_2d_tensor2.shape)
print(stacked_2d_tensor2)

torch.Size([2, 2, 2])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [10]:
stacked_2d_tensor3 = torch.stack((tensor_2d_1,tensor_2d_2),dim=2)
print(stacked_2d_tensor3.shape)
print(stacked_2d_tensor3)

torch.Size([2, 2, 2])
tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


CONCATENATION OPERATION

In [13]:
concatenated_tensors = torch.cat((tensor_2d_1,tensor_2d_2),dim=0)
print(concatenated_tensors.shape)
print(concatenated_tensors.ndim)
print(concatenated_tensors)

torch.Size([4, 2])
2
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [14]:
concatenated_tensors = torch.cat((tensor_2d_1,tensor_2d_2),dim=1)
print(concatenated_tensors.shape)
print(concatenated_tensors.ndim)
print(concatenated_tensors)

torch.Size([2, 4])
2
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
