<a href="https://colab.research.google.com/github/chanceCoderByPassion/DL_CV/blob/master/Intro_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
tensor = torch.arange(12)

In [4]:
reshaped_tensor_with_view=tensor.view(2,6)
reshaped_tensor_with_reshape=tensor.reshape(2,6)
print(reshaped_tensor_with_view)
print(reshaped_tensor_with_view.shape)
print(reshaped_tensor_with_reshape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [5]:
print("tensor is contiguous or not:",tensor.is_contiguous())

tensor is contiguous or not: True


In [7]:
inferred_shape=tensor.view(3,-1)
print(inferred_shape)
print(inferred_shape.size())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [9]:
tensor_3d=torch.arange(24).reshape(2,3,4)
print(tensor_3d)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [11]:
flattened=tensor_3d.view(-1)
print(flattened)
print("is_contiguous:",flattened.is_contiguous())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
is_contiguous: True


In [12]:
tensor_2d=torch.arange(24).reshape(12,2)
transposed_tensor=tensor_2d.t()
print(transposed_tensor.is_contiguous())

False
